services:
  - type: web
    name: manga-springboot
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/manga-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_DATASOURCE_URL
        value: jdbc:...
